# -*- coding: utf-8 -*-
"""NN_manuscript_github

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1csuen6jybLiz6O8mo9GivoFYe43fHOTq
"""

import os, time, math, json, random
from pathlib import Path
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision
import torchvision.transforms as T
from torch.utils.data import DataLoader, Subset

# =========================================================================
# CONFIGURATION
# =========================================================================
class Config:
    SPARSITY = 0.95
    SEEDS = [123]  # 3 seeds for statistical validity
    EPOCHS = 80
    BATCH = 128
    LR = 0.05
    RHO = 0.05
    WD_SGD = 5e-4   # Weight decay for SGD
    WD_SAM = 1e-3   # Weight decay for SAM variants (per SAM paper)

    RESULTS_DIR = Path('/content/sparse_sam_results')
    DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

CFG = Config()
CFG.RESULTS_DIR.mkdir(parents=True, exist_ok=True)

# =========================================================================
# RESNET-18 (CIFAR Variant)
# =========================================================================
class BasicBlock(nn.Module):
    def __init__(self, in_planes, planes, stride=1):
        super().__init__()
        self.conv1 = nn.Conv2d(in_planes, planes, 3, stride, 1, bias=False)
        self.bn1 = nn.BatchNorm2d(planes)
        self.conv2 = nn.Conv2d(planes, planes, 3, 1, 1, bias=False)
        self.bn2 = nn.BatchNorm2d(planes)
        self.shortcut = nn.Sequential()
        if stride != 1 or in_planes != planes:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_planes, planes, 1, stride, bias=False),
                nn.BatchNorm2d(planes))

    def forward(self, x):
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))
        out += self.shortcut(x)
        return F.relu(out)

class ResNetCIFAR(nn.Module):
    def __init__(self):
        super().__init__()
        self.in_planes = 64
        self.conv1 = nn.Conv2d(3, 64, 3, 1, 1, bias=False)
        self.bn1 = nn.BatchNorm2d(64)
        self.layer1 = self._layer(64, 2, 1)
        self.layer2 = self._layer(128, 2, 2)
        self.layer3 = self._layer(256, 2, 2)
        self.layer4 = self._layer(512, 2, 2)
        self.fc = nn.Linear(512, 10)

    def _layer(self, planes, blocks, stride):
        layers = [BasicBlock(self.in_planes, planes, stride)]
        self.in_planes = planes
        for _ in range(1, blocks):
            layers.append(BasicBlock(self.in_planes, planes))
        return nn.Sequential(*layers)

    def forward(self, x):
        x = F.relu(self.bn1(self.conv1(x)))
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)
        return self.fc(F.avg_pool2d(x, 4).view(x.size(0), -1))

# =========================================================================
# DENSE SAM (Standard SAM - All Parameters)
# =========================================================================
class DenseSAM(optim.Optimizer):
    """Standard SAM that perturbs ALL parameters"""
    def __init__(self, params, base_optimizer, rho=0.05, **kwargs):
        defaults = dict(rho=rho, **kwargs)
        super().__init__(params, defaults)
        self.base_optimizer = base_optimizer(self.param_groups, **kwargs)
        self.param_groups = self.base_optimizer.param_groups

    def _grad_norm(self):
        """Compute L2 norm of all gradients"""
        return torch.norm(torch.stack([
            p.grad.norm(2) for g in self.param_groups
            for p in g['params'] if p.grad is not None
        ]), 2)

    @torch.no_grad()
    def first_step(self, zero_grad=False):
        grad_norm = self._grad_norm()
        scale = self.defaults['rho'] / (grad_norm + 1e-12)

        for group in self.param_groups:
            for p in group['params']:
                if p.grad is None: continue
                e_w = p.grad * scale
                p.add_(e_w)  # Move to w + ε
                self.state[p]['e_w'] = e_w

        if zero_grad: self.zero_grad()

    @torch.no_grad()
    def second_step(self, zero_grad=False):
        # Revert perturbation
        for group in self.param_groups:
            for p in group['params']:
                if 'e_w' in self.state[p]:
                    p.sub_(self.state[p]['e_w'])  # Move back to w

        # Apply gradient update
        self.base_optimizer.step()
        if zero_grad: self.zero_grad()

    def zero_grad(self):
        self.base_optimizer.zero_grad()

# =========================================================================
# SPARSE SAM (Magnitude-Based with Optional Iso-Norm)
# =========================================================================
class SparseSAM(optim.Optimizer):
    """
    Magnitude-Based Sparse SAM
    - Selects top-k gradients by magnitude (dynamic mask)
    - Optional Iso-Norm correction to preserve perturbation radius
    """
    def __init__(self, params, base_optimizer, rho=0.05, sparsity=0.95,
                 isonorm=True, **kwargs):
        defaults = dict(rho=rho, **kwargs)
        super().__init__(params, defaults)
        self.base_optimizer = base_optimizer(self.param_groups, **kwargs)
        self.param_groups = self.base_optimizer.param_groups
        self.sparsity = sparsity
        self.isonorm = isonorm

    def _grad_norm(self):
        """Compute L2 norm of all gradients"""
        return torch.norm(torch.stack([
            p.grad.norm(2) for g in self.param_groups
            for p in g['params'] if p.grad is not None
        ]), 2)

    @torch.no_grad()
    def first_step(self, zero_grad=False):
        # Step 1: Compute dense perturbation
        grad_norm = self._grad_norm()
        dense_scale = self.defaults['rho'] / (grad_norm + 1e-12)

        # Step 2: Apply sparse masking (top-k by magnitude)
        total_sq_norm = 0.0
        for group in self.param_groups:
            for p in group['params']:
                if p.grad is None: continue

                # Dense perturbation
                e_dense = p.grad * dense_scale

                # Top-k masking by magnitude
                k = max(1, int(e_dense.numel() * (1 - self.sparsity)))
                flat = e_dense.abs().view(-1)
                _, indices = torch.topk(flat, k)

                mask = torch.zeros_like(flat)
                mask[indices] = 1.0

                # Sparse perturbation
                e_sparse = e_dense * mask.view_as(p)
                self.state[p]['e_w'] = e_sparse
                total_sq_norm += e_sparse.pow(2).sum().item()

        # Step 3: Optional Iso-Norm rescaling
        if self.isonorm:
            masked_norm = math.sqrt(total_sq_norm)
            renorm = self.defaults['rho'] / (masked_norm + 1e-12)
        else:
            renorm = 1.0

        # Step 4: Apply perturbation
        for group in self.param_groups:
            for p in group['params']:
                if 'e_w' in self.state[p]:
                    self.state[p]['e_w'] *= renorm
                    p.add_(self.state[p]['e_w'])

        if zero_grad: self.zero_grad()

    @torch.no_grad()
    def second_step(self, zero_grad=False):
        # Revert perturbation
        for group in self.param_groups:
            for p in group['params']:
                if 'e_w' in self.state[p]:
                    p.sub_(self.state[p]['e_w'])

        # Apply gradient update
        self.base_optimizer.step()
        if zero_grad: self.zero_grad()

    def zero_grad(self):
        self.base_optimizer.zero_grad()

# =========================================================================
# BATCH NORMALIZATION HELPERS (For SAM)
# =========================================================================
def disable_bn_running_stats(model):
    """Disable BN running stats during perturbed forward pass"""
    for m in model.modules():
        if isinstance(m, (nn.BatchNorm2d, nn.BatchNorm1d)):
            m.track_running_stats = False

def enable_bn_running_stats(model):
    """Re-enable BN running stats for normal training"""
    for m in model.modules():
        if isinstance(m, (nn.BatchNorm2d, nn.BatchNorm1d)):
            m.track_running_stats = True

# =========================================================================
# DATA LOADING
# =========================================================================
def get_cifar10_loaders(batch_size=128, num_workers=2, seed=42):
    """Get CIFAR-10 with 50% stratified subset"""
    mean = (0.4914, 0.4822, 0.4465)
    std = (0.2023, 0.1994, 0.2010)

    train_transform = T.Compose([
        T.RandomCrop(32, padding=4),
        T.RandomHorizontalFlip(),
        T.ToTensor(),
        T.Normalize(mean, std)
    ])

    test_transform = T.Compose([
        T.ToTensor(),
        T.Normalize(mean, std)
    ])

    # Full datasets
    train_full = torchvision.datasets.CIFAR10(
        './data', train=True, transform=train_transform, download=True
    )
    test_full = torchvision.datasets.CIFAR10(
        './data', train=False, transform=test_transform, download=True
    )

    # 50% stratified subset
    rng = np.random.RandomState(seed)
    targets = np.array(train_full.targets)
    indices = []
    for c in range(10):
        c_idx = np.where(targets == c)[0]
        rng.shuffle(c_idx)
        take = len(c_idx) // 2  # 50% per class
        indices.extend(c_idx[:take].tolist())

    train_subset = Subset(train_full, indices)

    train_loader = DataLoader(
        train_subset, batch_size=batch_size, shuffle=True,
        num_workers=num_workers, pin_memory=True, drop_last=True
    )
    test_loader = DataLoader(
        test_full, batch_size=batch_size, shuffle=False,
        num_workers=num_workers, pin_memory=True
    )

    return train_loader, test_loader, train_subset

# =========================================================================
# TRAINING FUNCTIONS
# =========================================================================
def train_epoch_sgd(model, train_loader, optimizer, criterion, device):
    """Standard SGD training (no SAM)"""
    model.train()
    total_loss = 0.0
    correct = 0
    total = 0

    for x, y in train_loader:
        x, y = x.to(device), y.to(device)

        optimizer.zero_grad()
        out = model(x)
        loss = criterion(out, y)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * x.size(0)
        correct += (out.argmax(1) == y).sum().item()
        total += y.size(0)

    return total_loss / total, 100.0 * correct / total

def train_epoch_sam(model, train_loader, optimizer, criterion, device):
    """SAM training (Dense or Sparse)"""
    model.train()
    total_loss = 0.0
    correct = 0
    total = 0
    perturb_norms = []

    for batch_idx, (x, y) in enumerate(train_loader):
        x, y = x.to(device), y.to(device)

        # First forward-backward (compute perturbation)
        optimizer.zero_grad()
        out = model(x)
        loss = criterion(out, y)
        loss.backward()

        # Apply perturbation
        disable_bn_running_stats(model)
        optimizer.first_step(zero_grad=True)

        # Log perturbation norm (first batch only for efficiency)
        if batch_idx == 0:
            sq_sum = sum(
                optimizer.state[p]['e_w'].pow(2).sum().item()
                for g in optimizer.param_groups
                for p in g['params']
                if 'e_w' in optimizer.state[p]
            )
            perturb_norms.append(math.sqrt(sq_sum))

        # Second forward-backward (at perturbed position)
        criterion(model(x), y).backward()

        # Update weights and revert perturbation
        enable_bn_running_stats(model)
        optimizer.second_step(zero_grad=True)

        total_loss += loss.item() * x.size(0)
        correct += (out.argmax(1) == y).sum().item()
        total += y.size(0)

    avg_perturb_norm = perturb_norms[0] if perturb_norms else 0.0
    return total_loss / total, 100.0 * correct / total, avg_perturb_norm

@torch.no_grad()
def evaluate(model, test_loader, device):
    """Evaluation"""
    model.eval()
    criterion = nn.CrossEntropyLoss()
    total_loss = 0.0
    correct = 0
    total = 0

    for x, y in test_loader:
        x, y = x.to(device), y.to(device)
        out = model(x)
        loss = criterion(out, y)

        total_loss += loss.item() * x.size(0)
        correct += (out.argmax(1) == y).sum().item()
        total += y.size(0)

    return total_loss / total, 100.0 * correct / total

# =========================================================================
# EXPERIMENT RUNNER
# =========================================================================
def run_experiment(method, seed):
    """Run single experiment for given method and seed"""
    fname = f"{method}_s{seed}_sp95.json"
    save_path = CFG.RESULTS_DIR / fname

    if save_path.exists():
        print(f"✓ Skipping {fname} (already exists)")
        return

    print(f"\n{'='*70}")
    print(f"Running: {method} | Seed: {seed}")
    print(f"{'='*70}")

    # Set seed
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    # Data
    train_loader, test_loader, train_dataset = get_cifar10_loaders(
        batch_size=CFG.BATCH, num_workers=2, seed=seed
    )

    # Model
    model = ResNetCIFAR().to(CFG.DEVICE)
    criterion = nn.CrossEntropyLoss()

    # Optimizer selection
    if method == 'sgd':
        optimizer = optim.SGD(
            model.parameters(), lr=CFG.LR, momentum=0.9,
            weight_decay=CFG.WD_SGD
        )
        scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, CFG.EPOCHS)
        is_sam = False

    elif method == 'sam_dense':
        base_opt = lambda params, **kwargs: optim.SGD(
            params, lr=CFG.LR, momentum=0.9, weight_decay=CFG.WD_SAM, **kwargs
        )
        optimizer = DenseSAM(model.parameters(), base_opt, rho=CFG.RHO)
        scheduler = optim.lr_scheduler.CosineAnnealingLR(
            optimizer.base_optimizer, CFG.EPOCHS
        )
        is_sam = True

    elif method == 'ssam_standard':
        base_opt = lambda params, **kwargs: optim.SGD(
            params, lr=CFG.LR, momentum=0.9, weight_decay=CFG.WD_SAM, **kwargs
        )
        optimizer = SparseSAM(
            model.parameters(), base_opt, rho=CFG.RHO,
            sparsity=CFG.SPARSITY, isonorm=False
        )
        scheduler = optim.lr_scheduler.CosineAnnealingLR(
            optimizer.base_optimizer, CFG.EPOCHS
        )
        is_sam = True

    elif method == 'ssam_isonorm':
        base_opt = lambda params, **kwargs: optim.SGD(
            params, lr=CFG.LR, momentum=0.9, weight_decay=CFG.WD_SAM, **kwargs
        )
        optimizer = SparseSAM(
            model.parameters(), base_opt, rho=CFG.RHO,
            sparsity=CFG.SPARSITY, isonorm=True
        )
        scheduler = optim.lr_scheduler.CosineAnnealingLR(
            optimizer.base_optimizer, CFG.EPOCHS
        )
        is_sam = True
    else:
        raise ValueError(f"Unknown method: {method}")

    # Training history
    history = {
        'train_loss': [], 'train_acc': [],
        'test_loss': [], 'test_acc': [],
        'perturb_norm': [], 'gen_gap': []
    }

    # Training loop
    for epoch in range(CFG.EPOCHS):
        start_time = time.time()

        # Train
        if is_sam:
            train_loss, train_acc, perturb_norm = train_epoch_sam(
                model, train_loader, optimizer, criterion, CFG.DEVICE
            )
        else:
            train_loss, train_acc = train_epoch_sgd(
                model, train_loader, optimizer, criterion, CFG.DEVICE
            )
            perturb_norm = 0.0

        # Evaluate
        test_loss, test_acc = evaluate(model, test_loader, CFG.DEVICE)

        # LR step
        scheduler.step()

        # Save metrics
        history['train_loss'].append(train_loss)
        history['train_acc'].append(train_acc)
        history['test_loss'].append(test_loss)
        history['test_acc'].append(test_acc)
        history['perturb_norm'].append(perturb_norm)
        history['gen_gap'].append(train_acc - test_acc)

        # Log
        if epoch % 10 == 0 or epoch == CFG.EPOCHS - 1:
            print(f"Epoch {epoch:3d} | Train: {train_acc:5.2f}% | "
                  f"Test: {test_acc:5.2f}% | Loss: {test_loss:.4f} | "
                  f"Norm: {perturb_norm:.4f} | Time: {time.time()-start_time:.1f}s")

    # Save results
    with open(save_path, 'w') as f:
        json.dump(history, f, indent=2)

    print(f"✓ Saved: {fname}")
    print(f"  Best Test Acc: {max(history['test_acc']):.2f}%")

# =========================================================================
# MAIN EXECUTION
# =========================================================================
if __name__ == "__main__":
    print(f"Device: {CFG.DEVICE}")
    print(f"Seeds: {CFG.SEEDS}")
    print(f"Epochs: {CFG.EPOCHS}")
    print(f"Sparsity: {CFG.SPARSITY}")

    methods = ['ssam_standard', 'ssam_isonorm']

    for method in methods:
        for seed in CFG.SEEDS:
            run_experiment(method, seed)

    print(f"\n{'='*70}")
    print("ALL EXPERIMENTS COMPLETE!")
    print(f"Results saved to: {CFG.RESULTS_DIR}")
    print(f"{'='*70}")

import json
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path
from scipy import stats

# ==========================================
# CONFIGURATION
# ==========================================
RESULTS_DIR = Path('/content/')

# Define method styling
METHODS = {
    'sgd':             {'label': 'SGD',                    'color': '#95A5A6', 'marker': 'o'},
    'sam_dense':       {'label': 'Dense SAM',              'color': '#3498DB', 'marker': 's'},
    'ssam_standard':   {'label': 'Standard Sparse SAM',    'color': '#E74C3C', 'marker': '^'},
    'ssam_isonorm':    {'label': 'Iso-Norm SSAM (Ours)',   'color': '#2ECC71', 'marker': 'D'}
}

SEEDS = [8, 42, 123]
RHO = 0.05
SPARSITY = 0.95
THEORETICAL_STANDARD_NORM = RHO * np.sqrt(1 - SPARSITY)  # ≈ 0.0112

# ==========================================
# DATA LOADING
# ==========================================
def load_all():
    data = {}
    print(f"Loading results from: {RESULTS_DIR}")

    # Initialize dictionary structure
    for method in METHODS.keys():
        data[method] = {
            'test_acc': [], 'train_loss': [], 'test_loss': [],
            'perturb_norm': [], 'gen_gap': []
        }

        for seed in SEEDS:
            fpath = RESULTS_DIR / f"{method}_s{seed}_sp95.json"
            if not fpath.exists():
                print(f"⚠️  Missing: {fpath}")
                continue

            with open(fpath) as f:
                run = json.load(f)
                # Load all metrics safely
                for key in data[method].keys():
                    if key in run:
                        data[method][key].append(run[key])

    # Calculate Mean/Std Statistics
    stats_data = {}
    for method, runs in data.items():
        stats_data[method] = {}
        # Iterate over all 5 metrics
        for metric in ['test_acc', 'train_loss', 'test_loss', 'perturb_norm', 'gen_gap']:
            arr = np.array(runs[metric])
            if len(arr) == 0:
                continue

            # Align lengths if runs crashed/stopped early
            min_len = min(len(a) for a in arr)
            arr = np.array([a[:min_len] for a in arr])

            # Determine "best" (Max for Acc, Min for Loss/Gap)
            if 'acc' in metric:
                best_fn = np.max
            else:
                best_fn = np.min

            stats_data[method][metric] = {
                'mean': np.mean(arr, axis=0),
                'std': np.std(arr, axis=0),
                'best_mean': best_fn(np.mean(arr, axis=0)),
                'best_std': np.std([best_fn(run) for run in arr])
            }

    return data, stats_data

# ==========================================
# PLOTTING
# ==========================================
def plot_all(stats_data):
    # Create 2x3 grid (2 Rows, 3 Columns)
    fig, axes = plt.subplots(2, 3, figsize=(20, 12))

    # Helper to plot mean +/- std
    def plot_metric(ax, metric_key, title, ylabel, log_scale=False):
        for method, style in METHODS.items():
            if method not in stats_data or metric_key not in stats_data[method]: continue

            d = stats_data[method][metric_key]
            epochs = np.arange(len(d['mean']))

            ax.plot(epochs, d['mean'], label=style['label'], color=style['color'], linewidth=2)
            ax.fill_between(epochs, d['mean'] - d['std'], d['mean'] + d['std'], alpha=0.15, color=style['color'])

        ax.set_xlabel('Epoch', fontsize=11)
        ax.set_ylabel(ylabel, fontsize=11)
        ax.set_title(title, fontweight='bold', fontsize=12)
        ax.grid(True, alpha=0.3, which='both')
        if log_scale: ax.set_yscale('log')
        if metric_key == 'test_acc': ax.legend(fontsize=9, loc='lower right')

    # --- Row 1: Performance Metrics ---
    plot_metric(axes[0, 0], 'test_acc', '(a) Test Accuracy (Higher is Better)', 'Accuracy (%)')
    # Train loss in Log scale to see convergence at 10^-3
    plot_metric(axes[0, 1], 'train_loss', '(b) Training Loss (Log Scale)', 'Loss', log_scale=True)
    # Test loss linear to see overfitting/stability
    plot_metric(axes[0, 2], 'test_loss', '(c) Test Loss (Lower is Better)', 'Loss')

    # --- Row 2: Analysis Metrics ---

    # (d) Perturbation Norms (The Mechanism)
    ax = axes[1, 0]
    ax.axhline(y=RHO, color='black', linestyle='--', linewidth=2, label=f'Target ρ={RHO}')
    ax.axhline(y=THEORETICAL_STANDARD_NORM, color='gray', linestyle=':', linewidth=2, label=f'Theory ≈{THEORETICAL_STANDARD_NORM:.4f}')

    for method, style in METHODS.items():
        if method == 'sgd' or method not in stats_data: continue
        d = stats_data[method]['perturb_norm']
        norms = d['mean']
        # Filter sparse logs (usually logged once per epoch, but handle 0s just in case)
        valid_idxs = [i for i, n in enumerate(norms) if n > 1e-6]
        if not valid_idxs: continue

        ax.plot(np.array(valid_idxs), norms[valid_idxs], label=style['label'], color=style['color'],
                linewidth=2.5, marker=style['marker'], markersize=6, markevery=10)

    ax.set_xlabel('Epoch'); ax.set_ylabel('||ε||₂')
    ax.set_title('(d) Perturbation Norm Stability', fontweight='bold', fontsize=12)
    ax.legend(fontsize=9); ax.grid(True, alpha=0.3)
    ax.set_ylim(0, 0.06) # Focus on the relevant range

    # (e) Generalization Gap
    plot_metric(axes[1, 1], 'gen_gap', '(e) Generalization Gap', 'Train - Test Acc (%)')

    # (f) Final Bar Chart (The Result)
    ax = axes[1, 2]
    methods_list = list(METHODS.keys())
    best_accs = [stats_data[m]['test_acc']['best_mean'] if m in stats_data and 'test_acc' in stats_data[m] else 0 for m in methods_list]
    best_stds = [stats_data[m]['test_acc']['best_std'] if m in stats_data and 'test_acc' in stats_data[m] else 0 for m in methods_list]

    # Clean labels for bar chart
    labels = [METHODS[m]['label'].replace('Sparse SAM', 'SSAM').replace(' (Ours)', '') for m in methods_list]
    colors = [METHODS[m]['color'] for m in methods_list]

    x = np.arange(len(methods_list))
    ax.bar(x, best_accs, yerr=best_stds, capsize=5, color=colors, alpha=0.8, edgecolor='black')

    # Add value text on bars
    for i, (acc, std) in enumerate(zip(best_accs, best_stds)):
        ax.text(i, acc + std + 0.1, f'{acc:.1f}%', ha='center', fontweight='bold', fontsize=10)

    ax.set_xticks(x); ax.set_xticklabels(labels, rotation=15, ha='right')
    ax.set_title('(f) Final Performance', fontweight='bold', fontsize=12)
    ax.set_ylim(bottom=90); ax.grid(True, alpha=0.3, axis='y')

    # Final Layout
    plt.suptitle('Complete Analysis of Iso-Norm Sparse SAM (95% Sparsity)', fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.subplots_adjust(top=0.90, hspace=0.3)

    save_path = RESULTS_DIR / 'all_results_6panel.png'
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    print(f"✓ Saved plot to: {save_path}")
    plt.show()

# ==========================================
# TEXT SUMMARY
# ==========================================
def print_stats(stats_data):
    print("\n" + "="*80)
    print("STATISTICAL SUMMARY (Mean ± Std over 3 Seeds)")
    print("="*80)
    print(f"{'Method':<30} | {'Best Acc':<20} | {'Final Acc'}")
    print("-"*80)

    for method in METHODS.keys():
        if method not in stats_data or 'test_acc' not in stats_data[method]:
            print(f"{METHODS[method]['label']:<30} | N/A")
            continue

        label = METHODS[method]['label']
        d = stats_data[method]['test_acc']

        print(f"{label:<30} | {d['best_mean']:6.2f} ± {d['best_std']:4.2f}%     | {d['mean'][-1]:6.2f}%")
    print("="*80)

# ==========================================
# MAIN EXECUTION
# ==========================================
if __name__ == "__main__":
    raw_data, stats = load_all()
    if stats:
        plot_all(stats)
        print_stats(stats)
    else:
        print("No data found! Run experiments first.")

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
from pathlib import Path

# Config
SAVE_DIR = Path('/content/manuscript_figures')
SAVE_DIR.mkdir(parents=True, exist_ok=True)

def plot_conceptual_figure_fixed():
    fig, ax = plt.subplots(figsize=(8, 8))

    # 1. Setup the "Weight Space"
    rho = 1.0
    ax.set_xlim(-1.3, 1.3)
    ax.set_ylim(-1.3, 1.3)
    ax.set_aspect('equal')

    # Remove axes ticks for clean look
    ax.axis('off')

    # 2. Draw the Neighborhood Ball (Radius rho)
    # Zorder 0 ensures it is behind everything
    circle = plt.Circle((0, 0), rho, color='#F8F9F9', ec='black', ls='--', lw=1.5, zorder=0)
    ax.add_artist(circle)
    ax.text(0.65, 0.9, r'$\rho$-Neighborhood', fontsize=12, color='#555555')

    # 3. Define Vectors
    # Dense Vector (Blue) - touches boundary
    angle_dense = np.deg2rad(55)
    dense_vec = np.array([np.cos(angle_dense), np.sin(angle_dense)]) * rho

    # Sparse Vector (Red) - collapsed inside
    angle_sparse = np.deg2rad(30)
    collapse_factor = 0.45
    sparse_vec = np.array([np.cos(angle_sparse), np.sin(angle_sparse)]) * (rho * collapse_factor)

    # Iso-Norm Vector (Green) - touches boundary, collinear with Sparse
    isonorm_vec = np.array([np.cos(angle_sparse), np.sin(angle_sparse)]) * rho

    # 4. Plot Vectors using annotate (Better head control)
    def draw_vector(vec, color, label_text, label_pos):
        # Draw the arrow
        ax.annotate('', xy=(vec[0], vec[1]), xytext=(0, 0),
                    arrowprops=dict(facecolor=color, edgecolor=color, width=3, headwidth=10, shrink=0.0),
                    zorder=5)
        # Draw the label with a white box background
        ax.text(label_pos[0], label_pos[1], label_text, color=color, fontsize=11, fontweight='bold',
                bbox=dict(facecolor='white', edgecolor='none', alpha=0.8, pad=1))

    # Draw Dense (Blue)
    draw_vector(dense_vec, '#3498DB', r'Dense SAM $(\epsilon_{dense})$',
                (dense_vec[0] + 0.05, dense_vec[1]))

    # Draw Iso-Norm (Green)
    draw_vector(isonorm_vec, '#2ECC71', r'Iso-Norm SSAM $(\epsilon_{iso})$',
                (isonorm_vec[0] + 0.05, isonorm_vec[1] - 0.05))

    # Draw Sparse (Red)
    draw_vector(sparse_vec, '#E74C3C', '', (0,0)) # No label at tip
    ax.text(sparse_vec[0] + 0.05, sparse_vec[1] - 0.15,
            r'Standard SSAM' + '\n' + r'(Collapsed)',
            fontsize=10, color='#E74C3C', ha='left', va='top')

    # 5. Add "Rescaling" Annotation
    # Curve arrow from Red tip to Green tip
    # We use a fancy arrow patch to connect them
    arrow = patches.FancyArrowPatch((sparse_vec[0], sparse_vec[1]),
                                    (isonorm_vec[0]*0.95, isonorm_vec[1]*0.95), # Stop slightly short of tip
                                    connectionstyle="arc3,rad=0",
                                    arrowstyle="->", color='black', lw=1.5, ls=':')
    ax.add_patch(arrow)

    # Label for the rescaling
    mid_x = (sparse_vec[0] + isonorm_vec[0]) / 2
    mid_y = (sparse_vec[1] + isonorm_vec[1]) / 2
    ax.text(mid_x + 0.05, mid_y - 0.1, r'Rescaling ($\gamma$)', fontsize=10, rotation=30)

    # Center Point
    ax.plot(0, 0, 'ko', markersize=6, zorder=10)
    ax.text(-0.15, -0.15, r'$w_t$', fontsize=14, fontweight='bold')

    plt.title('Geometric Visualization of Norm Correction', fontsize=14, fontweight='bold')
    plt.tight_layout()

    filename = SAVE_DIR / 'fig6_concept_fixed.png'
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    print(f"✓ Saved fixed conceptual figure: {filename}")
    plt.show()

if __name__ == "__main__":
    plot_conceptual_figure_fixed()

import json
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

# ==========================================
# CONFIGURATION
# ==========================================
RESULTS_DIR = Path('/content/')
SAVE_DIR = Path('/content/manuscript_figures')
SAVE_DIR.mkdir(parents=True, exist_ok=True)

METHODS = {
    'sgd':             {'label': 'SGD',                    'color': '#95A5A6', 'marker': 'o'},
    'sam_dense':       {'label': 'Dense SAM',              'color': '#3498DB', 'marker': 's'},
    'ssam_standard':   {'label': 'Standard Sparse SAM',    'color': '#E74C3C', 'marker': '^'},
    'ssam_isonorm':    {'label': 'Iso-Norm SSAM (Ours)',   'color': '#2ECC71', 'marker': 'D'}
}

SEEDS = [8, 42, 123]
RHO = 0.05
SPARSITY = 0.95
THEORETICAL_STANDARD_NORM = RHO * np.sqrt(1 - SPARSITY)

# ==========================================
# DATA LOADING
# ==========================================
def load_all():
    data = {}
    for method in METHODS.keys():
        data[method] = {'test_acc': [], 'test_loss': [], 'perturb_norm': [], 'gen_gap': []}
        for seed in SEEDS:
            fpath = RESULTS_DIR / f"{method}_s{seed}_sp95.json"
            if fpath.exists():
                with open(fpath) as f:
                    run = json.load(f)
                    for key in data[method].keys():
                        if key in run: data[method][key].append(run[key])

    stats_data = {}
    for method, runs in data.items():
        stats_data[method] = {}
        for metric in runs.keys():
            arr = np.array(runs[metric])
            if len(arr) == 0: continue
            min_len = min(len(a) for a in arr)
            arr = np.array([a[:min_len] for a in arr])
            stats_data[method][metric] = {
                'mean': np.mean(arr, axis=0),
                'std': np.std(arr, axis=0),
                'best_mean': np.max(np.mean(arr, axis=0)) if 'acc' in metric else np.min(np.mean(arr, axis=0)),
                'best_std': np.std([np.max(run) for run in arr]) if 'acc' in metric else np.std([np.min(run) for run in arr])
            }
    return stats_data

# ==========================================
# INDIVIDUAL PLOTTING FUNCTIONS
# ==========================================
def save_plot(filename, title, ylabel, stats_data, metric_key, is_norm=False):
    plt.figure(figsize=(8, 6))
    if is_norm:
        plt.axhline(y=RHO, color='black', linestyle='--', linewidth=1.5, label=f'Target ρ={RHO}', zorder=1)
        plt.axhline(y=THEORETICAL_STANDARD_NORM, color='gray', linestyle=':', linewidth=2, label=f'Theory ≈{THEORETICAL_STANDARD_NORM:.4f}', zorder=1)

    for method, style in METHODS.items():
        if method not in stats_data or metric_key not in stats_data[method]: continue
        d = stats_data[method][metric_key]
        epochs = np.arange(len(d['mean']))

        if is_norm:
            # Clean logging for norms (ignore 0s)
            valid = [i for i, n in enumerate(d['mean']) if n > 1e-6]
            if not valid: continue

            # --- OVERLAP FIX FOR FIG 2 ---
            # Make Dense SAM a thick dashed line so it's visible behind the solid green line
            ls = '--' if method == 'sam_dense' else '-'
            lw = 4.0 if method == 'sam_dense' else 2.5
            zo = 2 if method == 'sam_dense' else 3 # Put Iso-norm on top

            plt.plot(np.array(valid), d['mean'][valid], label=style['label'], color=style['color'],
                     linewidth=lw, marker=style['marker'], markersize=6, markevery=10,
                     linestyle=ls, zorder=zo)
        else:
            plt.plot(epochs, d['mean'], label=style['label'], color=style['color'], linewidth=2)
            plt.fill_between(epochs, d['mean'] - d['std'], d['mean'] + d['std'], alpha=0.15, color=style['color'])

    plt.title(title, fontweight='bold', fontsize=14)
    plt.xlabel('Epoch', fontsize=12); plt.ylabel(ylabel, fontsize=12)
    plt.grid(True, alpha=0.3); plt.legend(fontsize=10)

    if is_norm:
        plt.ylim(0, 0.06) # Keep focus on the target area

    plt.tight_layout()
    plt.savefig(SAVE_DIR / filename, dpi=300)
    plt.close()
    print(f"✓ Saved: {filename}")

def save_bar_chart(stats_data):
    plt.figure(figsize=(9, 6))
    methods_list = [m for m in METHODS.keys() if m in stats_data]
    best_accs = [stats_data[m]['test_acc']['best_mean'] for m in methods_list]
    best_stds = [stats_data[m]['test_acc']['best_std'] for m in methods_list]
    labels = [METHODS[m]['label'].replace(' (Ours)', '') for m in methods_list]
    colors = [METHODS[m]['color'] for m in methods_list]

    x = np.arange(len(methods_list))
    bars = plt.bar(x, best_accs, yerr=best_stds, capsize=7, color=colors, alpha=0.8, edgecolor='black')
    for i, (acc, std) in enumerate(zip(best_accs, best_stds)):
        plt.text(i, acc + std + 0.1, f'{acc:.2f}%', ha='center', fontweight='bold')

    plt.xticks(x, labels, rotation=15); plt.ylabel('Best Test Accuracy (%)', fontsize=12)
    plt.title('Final Performance Comparison (95% Sparsity)', fontweight='bold', fontsize=14)
    plt.ylim(bottom=min(best_accs)-1); plt.grid(True, alpha=0.3, axis='y')
    plt.tight_layout()
    plt.savefig(SAVE_DIR / 'fig_final_bar_chart.png', dpi=300)
    plt.close()
    print(f"✓ Saved: fig_final_bar_chart.png")

# ==========================================
# EXECUTION
# ==========================================
if __name__ == "__main__":
    stats = load_all()
    if stats:
        save_plot('fig1_test_accuracy.png', 'Test Accuracy Comparison', 'Accuracy (%)', stats, 'test_acc')
        # Figure 2 now handles overlapping Dense/Iso-norm lines
        save_plot('fig2_perturbation_norm.png', 'Perturbation Norm Stability', '||ε||₂', stats, 'perturb_norm', is_norm=True)
        save_plot('fig3_gen_gap.png', 'Generalization Gap (Overfitting)', 'Train - Test Acc (%)', stats, 'gen_gap')
        save_plot('fig4_test_loss.png', 'Test Loss Convergence', 'Cross Entropy Loss', stats, 'test_loss')
        save_bar_chart(stats)
        print(f"\n🚀 All figures saved individually to: {SAVE_DIR}")
    else:
        print("Error: No data found in RESULTS_DIR.")

